
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 02 14:26:32 VET 2013
//----------------------------------------------------

package Interprete;

import java_cup.runtime.*;
import nodos.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu May 02 14:26:32 VET 2013
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\002\003\000\002\002\004\000\002\002" +
    "\005\000\002\002\005\000\002\002\005\000\002\002\005" +
    "\000\002\002\005\000\002\002\005\000\002\002\007\000" +
    "\002\002\007\000\002\003\005\000\002\003\007\000\002" +
    "\003\007\000\002\003\007\000\002\003\005\000\002\003" +
    "\003\000\002\004\003\000\002\004\005\000\002\004\005" +
    "\000\002\004\005\000\002\004\005\000\002\004\005\000" +
    "\002\004\005\000\002\004\005\000\002\004\005\000\002" +
    "\004\005\000\002\004\005\000\002\006\003\000\002\006" +
    "\004\000\002\005\003\000\002\005\005\000\002\005\003" +
    "\000\002\005\003\000\002\005\005\000\002\005\005\000" +
    "\002\005\005\000\002\005\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\115\000\010\004\006\005\007\037\004\001\002\000" +
    "\024\002\uffe6\006\uffe6\007\uffe6\010\uffe6\011\uffe6\012\uffe6" +
    "\013\uffe6\032\uffe6\037\117\001\002\000\022\002\001\006" +
    "\001\007\001\010\001\011\001\012\001\013\001\032\001" +
    "\001\002\000\014\031\030\034\033\035\031\036\027\037" +
    "\026\001\002\000\014\031\030\034\033\035\031\036\027" +
    "\037\026\001\002\000\020\002\015\006\013\007\011\010" +
    "\012\011\017\012\014\013\016\001\002\000\010\004\006" +
    "\005\007\037\004\001\002\000\010\004\006\005\007\037" +
    "\004\001\002\000\010\004\006\005\007\037\004\001\002" +
    "\000\010\004\006\005\007\037\004\001\002\000\004\002" +
    "\000\001\002\000\010\004\006\005\007\037\004\001\002" +
    "\000\010\004\006\005\007\037\004\001\002\000\022\002" +
    "\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012\ufffe\013\ufffe" +
    "\032\ufffe\001\002\000\022\002\ufffa\006\ufffa\007\ufffa\010" +
    "\ufffa\011\ufffa\012\ufffa\013\ufffa\032\ufffa\001\002\000\022" +
    "\002\ufffd\006\ufffd\007\ufffd\010\ufffd\011\ufffd\012\ufffd\013" +
    "\ufffd\032\ufffd\001\002\000\022\002\uffff\006\uffff\007\uffff" +
    "\010\uffff\011\uffff\012\uffff\013\uffff\032\uffff\001\002\000" +
    "\022\002\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb" +
    "\013\ufffb\032\ufffb\001\002\000\022\002\ufffc\006\ufffc\007" +
    "\ufffc\010\ufffc\011\ufffc\012\ufffc\013\ufffc\032\ufffc\001\002" +
    "\000\042\014\uffe4\015\uffe4\016\uffe4\017\uffe4\020\uffe4\021" +
    "\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\026\uffe4\027\uffe4" +
    "\030\uffe4\031\uffe4\032\uffe4\033\uffe4\001\002\000\042\014" +
    "\uffe2\015\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022\uffe2" +
    "\023\uffe2\024\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031" +
    "\uffe2\032\uffe2\033\uffe2\001\002\000\014\031\065\034\033" +
    "\035\031\036\027\037\026\001\002\000\042\014\uffe1\015" +
    "\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1\022\uffe1\023\uffe1" +
    "\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030\uffe1\031\uffe1\032" +
    "\uffe1\033\uffe1\001\002\000\006\031\075\033\076\001\002" +
    "\000\004\037\073\001\002\000\014\014\063\015\062\016" +
    "\064\031\ufff2\033\ufff2\001\002\000\042\014\ufff1\015\ufff1" +
    "\016\ufff1\017\042\020\047\021\044\022\043\023\037\024" +
    "\045\025\040\026\046\027\041\030\036\031\ufff1\032\ufff1" +
    "\033\ufff1\001\002\000\012\034\033\035\031\036\027\037" +
    "\026\001\002\000\012\034\033\035\031\036\027\037\026" +
    "\001\002\000\012\034\033\035\031\036\027\037\026\001" +
    "\002\000\012\034\033\035\031\036\027\037\026\001\002" +
    "\000\012\034\033\035\031\036\027\037\026\001\002\000" +
    "\012\034\033\035\031\036\027\037\026\001\002\000\012" +
    "\034\033\035\031\036\027\037\026\001\002\000\012\034" +
    "\033\035\031\036\027\037\026\001\002\000\012\034\033" +
    "\035\031\036\027\037\026\001\002\000\012\034\033\035" +
    "\031\036\027\037\026\001\002\000\026\014\uffef\015\uffef" +
    "\016\uffef\025\040\026\046\027\041\030\036\031\uffef\032" +
    "\uffef\033\uffef\001\002\000\042\014\uffdf\015\uffdf\016\uffdf" +
    "\017\uffdf\020\uffdf\021\uffdf\022\uffdf\023\uffdf\024\uffdf\025" +
    "\uffdf\026\uffdf\027\041\030\036\031\uffdf\032\uffdf\033\uffdf" +
    "\001\002\000\026\014\uffed\015\uffed\016\uffed\025\040\026" +
    "\046\027\041\030\036\031\uffed\032\uffed\033\uffed\001\002" +
    "\000\026\014\uffec\015\uffec\016\uffec\025\040\026\046\027" +
    "\041\030\036\031\uffec\032\uffec\033\uffec\001\002\000\026" +
    "\014\uffeb\015\uffeb\016\uffeb\025\040\026\046\027\041\030" +
    "\036\031\uffeb\032\uffeb\033\uffeb\001\002\000\026\014\ufff0" +
    "\015\ufff0\016\ufff0\025\040\026\046\027\041\030\036\031" +
    "\ufff0\032\ufff0\033\ufff0\001\002\000\042\014\uffde\015\uffde" +
    "\016\uffde\017\uffde\020\uffde\021\uffde\022\uffde\023\uffde\024" +
    "\uffde\025\uffde\026\uffde\027\uffde\030\uffde\031\uffde\032\uffde" +
    "\033\uffde\001\002\000\042\014\uffe0\015\uffe0\016\uffe0\017" +
    "\uffe0\020\uffe0\021\uffe0\022\uffe0\023\uffe0\024\uffe0\025\uffe0" +
    "\026\uffe0\027\041\030\036\031\uffe0\032\uffe0\033\uffe0\001" +
    "\002\000\026\014\uffee\015\uffee\016\uffee\025\040\026\046" +
    "\027\041\030\036\031\uffee\032\uffee\033\uffee\001\002\000" +
    "\042\014\uffdd\015\uffdd\016\uffdd\017\uffdd\020\uffdd\021\uffdd" +
    "\022\uffdd\023\uffdd\024\uffdd\025\uffdd\026\uffdd\027\uffdd\030" +
    "\uffdd\031\uffdd\032\uffdd\033\uffdd\001\002\000\014\031\065" +
    "\034\033\035\031\036\027\037\026\001\002\000\014\031" +
    "\065\034\033\035\031\036\027\037\026\001\002\000\014" +
    "\031\065\034\033\035\031\036\027\037\026\001\002\000" +
    "\012\034\033\035\031\036\027\037\026\001\002\000\016" +
    "\014\uffe9\015\uffe9\016\uffe9\031\uffe9\032\uffe9\033\uffe9\001" +
    "\002\000\014\025\040\026\046\027\041\030\036\032\070" +
    "\001\002\000\016\014\uffe7\015\uffe7\016\uffe7\031\uffe7\032" +
    "\uffe7\033\uffe7\001\002\000\016\014\uffea\015\uffea\016\uffea" +
    "\031\uffea\032\uffea\033\uffea\001\002\000\016\014\uffe8\015" +
    "\uffe8\016\uffe8\031\uffe8\032\uffe8\033\uffe8\001\002\000\004" +
    "\034\074\001\002\000\042\014\uffe3\015\uffe3\016\uffe3\017" +
    "\uffe3\020\uffe3\021\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3" +
    "\026\uffe3\027\uffe3\030\uffe3\031\uffe3\032\uffe3\033\uffe3\001" +
    "\002\000\010\004\006\005\007\037\004\001\002\000\014" +
    "\031\065\034\033\035\031\036\027\037\026\001\002\000" +
    "\014\014\063\015\062\016\064\031\ufff7\033\ufff7\001\002" +
    "\000\020\006\013\007\011\010\012\011\017\012\014\013" +
    "\016\032\101\001\002\000\022\002\ufff8\006\ufff8\007\ufff8" +
    "\010\ufff8\011\ufff8\012\ufff8\013\ufff8\032\ufff8\001\002\000" +
    "\012\014\063\015\062\016\064\032\104\001\002\000\036" +
    "\014\ufff1\015\ufff1\016\ufff1\017\042\020\047\021\044\022" +
    "\043\023\037\024\045\025\040\026\046\027\041\030\036" +
    "\032\070\001\002\000\014\014\106\015\105\016\107\031" +
    "\ufff3\033\ufff3\001\002\000\014\031\030\034\033\035\031" +
    "\036\027\037\026\001\002\000\014\031\030\034\033\035" +
    "\031\036\027\037\026\001\002\000\014\031\030\034\033" +
    "\035\031\036\027\037\026\001\002\000\006\031\ufff5\033" +
    "\ufff5\001\002\000\006\031\ufff6\033\ufff6\001\002\000\006" +
    "\031\ufff4\033\ufff4\001\002\000\006\031\114\033\076\001" +
    "\002\000\010\004\006\005\007\037\004\001\002\000\020" +
    "\006\013\007\011\010\012\011\017\012\014\013\016\032" +
    "\116\001\002\000\022\002\ufff9\006\ufff9\007\ufff9\010\ufff9" +
    "\011\ufff9\012\ufff9\013\ufff9\032\ufff9\001\002\000\022\002" +
    "\uffe5\006\uffe5\007\uffe5\010\uffe5\011\uffe5\012\uffe5\013\uffe5" +
    "\032\uffe5\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\115\000\006\002\007\006\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\003\112\004\033\005\034" +
    "\001\001\000\010\003\031\004\033\005\034\001\001\000" +
    "\002\001\001\000\006\002\024\006\004\001\001\000\006" +
    "\002\023\006\004\001\001\000\006\002\022\006\004\001" +
    "\001\000\006\002\021\006\004\001\001\000\002\001\001" +
    "\000\006\002\020\006\004\001\001\000\006\002\017\006" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\004\101" +
    "\005\102\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\060\001\001\000\004\005\057\001\001\000\004\005" +
    "\056\001\001\000\004\005\055\001\001\000\004\005\054" +
    "\001\001\000\004\005\053\001\001\000\004\005\052\001" +
    "\001\000\004\005\051\001\001\000\004\005\050\001\001" +
    "\000\004\005\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\004\071\005\034" +
    "\001\001\000\006\004\070\005\034\001\001\000\006\004" +
    "\065\005\034\001\001\000\004\005\066\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\002\077\006\004\001\001\000\006\004\076\005" +
    "\034\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\003\111\004\033\005\034\001\001\000\010" +
    "\003\110\004\033\005\034\001\001\000\010\003\107\004" +
    "\033\005\034\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\002\114\006" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




/***********
SymbolFactory es una nueva caracteristica que ha sido añadida a las version 11a de cup, la cual facilita la implementacion de clases Symbol personalizadas
, esto debido a que dicha clase no provee mucha información de contexto que podria ser util para el analisis semantico o ayudar en la construccion del AST
Mas informacion en: http//4thmouse.com/index.php/2007/02/15/using-custom-symbols-in-cup/
***********/
	public static void main(String args[]) throws Exception {
		//TinySymbolFactory sf = new TinySymbolFactory();
		SymbolFactory sf = new DefaultSymbolFactory();
		if (args.length==0) 
			new parser(new Scanner(System.in,sf),sf).parse();
		else 
			new parser(new Scanner(new java.io.FileInputStream(args[0]),sf),sf).parse();
			

	}


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {



			private boolean debug = true;
			private NodoBase raiz=null;
			
			public NodoBase getRaiz(){
				return raiz;
			}
			
			
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // nombre ::= nombre DIVI nombre 
            {
              NodoBase RESULT =null;
		int opeIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int opeIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase opeI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opeDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int opeDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase opeD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // nombre ::= nombre MULTI nombre 
            {
              NodoBase RESULT =null;
		int opeIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int opeIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase opeI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opeDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int opeDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase opeD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // nombre ::= nombre RESTA nombre 
            {
              NodoBase RESULT =null;
		int opeIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int opeIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase opeI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opeDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int opeDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase opeD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // nombre ::= nombre SUMA nombre 
            {
              NodoBase RESULT =null;
		int opeIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int opeIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase opeI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opeDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int opeDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase opeD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						/*RESULT = new NodoComparacion(opeI,tipoOp.suma,opeD);*/
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // nombre ::= FECHA 
            {
              NodoBase RESULT =null;
		int fechaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fecharight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object fecha = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // nombre ::= NUM 
            {
              NodoBase RESULT =null;
		int numeroleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numeroright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer numero = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // nombre ::= COMI ID COMI 
            {
              NodoBase RESULT =null;
		int palabraleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int palabraright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String palabra = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // nombre ::= ID 
            {
              NodoBase RESULT =null;
		int palabraleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int palabraright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String palabra = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // relacion ::= ID ID 
            {
              NodoBase RESULT =null;
		int palabraleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int palabraright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String palabra = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sinonimoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sinonimoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String sinonimo = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("relacion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // relacion ::= ID 
            {
              NodoBase RESULT =null;
		int palabraleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int palabraright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String palabra = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("relacion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // restriccion ::= IPAREN nombre DPAREN 
            {
              NodoBase RESULT =null;
		int operacionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int operacionright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase operacion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // restriccion ::= restriccion NOT restriccion 
            {
              NodoBase RESULT =null;
		int resIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int resIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase resI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int resDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int resDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase resD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // restriccion ::= restriccion OR restriccion 
            {
              NodoBase RESULT =null;
		int resIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int resIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase resI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int resDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int resDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase resD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // restriccion ::= restriccion AND restriccion 
            {
              NodoBase RESULT =null;
		int resIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int resIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase resI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int resDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int resDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase resD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // restriccion ::= nombre MAYOREQ nombre 
            {
              NodoBase RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase campo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // restriccion ::= nombre MAYOR nombre 
            {
              NodoBase RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase campo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // restriccion ::= nombre MENOREQ nombre 
            {
              NodoBase RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase campo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // restriccion ::= nombre MENOR nombre 
            {
              NodoBase RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase campo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // restriccion ::= nombre DIFERENTE nombre 
            {
              NodoBase RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase campo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // restriccion ::= nombre EQ nombre 
            {
              NodoBase RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase campo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						/*RESULT = new NodoComparacion(campo,tipoOp.igual,condicion);*/
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // restriccion ::= nombre 
            {
              NodoBase RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase campo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("restriccion",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // predicado ::= restriccion 
            {
              NodoBase RESULT =null;
		int restriccionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restriccionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase restriccion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("predicado",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // predicado ::= IPAREN restriccion DPAREN 
            {
              NodoBase RESULT =null;
		int condicionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int condicionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase condiciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("predicado",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // predicado ::= IPAREN restriccion DPAREN NOT predicado 
            {
              NodoBase RESULT =null;
		int condicionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int condicionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase condiciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int restriccionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restriccionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase restricciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("predicado",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // predicado ::= IPAREN restriccion DPAREN OR predicado 
            {
              NodoBase RESULT =null;
		int condicionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int condicionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase condiciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int restriccionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restriccionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase restricciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("predicado",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // predicado ::= IPAREN restriccion DPAREN AND predicado 
            {
              NodoBase RESULT =null;
		int condicionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int condicionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase condiciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int restriccionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restriccionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase restricciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("predicado",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // predicado ::= predicado COMA restriccion 
            {
              NodoBase RESULT =null;
		int condicionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condicionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase condiciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int restriccionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restriccionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase restriccion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		

					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("predicado",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expresion ::= PRO predicado IPAREN expresion DPAREN 
            {
              NodoBase RESULT =null;
		int restriccionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int restriccionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase restricciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase exp = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
						if(raiz==null){
							raiz = new NodoExpresion(sym.PRO,restricciones,exp);
						}else{
							NodoBase aux = raiz;
							while(aux.tieneHermano()) 
								aux = aux.getHermanoDerecha();
							aux.setHermanoDerecha(new NodoExpresion(sym.PRO,restricciones,exp));
						}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expresion ::= SEL predicado IPAREN expresion DPAREN 
            {
              NodoBase RESULT =null;
		int restriccionesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int restriccionesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase restricciones = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase exp = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
						if(raiz==null){
								raiz = new NodoExpresion(sym.SEL,restricciones,exp);
						}else{
							NodoBase aux = raiz;
							while(aux.tieneHermano()) 
								aux = aux.getHermanoDerecha();
							aux.setHermanoDerecha(new NodoExpresion(sym.SEL,restricciones,exp));
						}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expresion ::= expresion REUN expresion 
            {
              NodoBase RESULT =null;
		int condicionIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condicionIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase condicionI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicionD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						if(raiz==null){
							raiz = new NodoOperacion(sym.REUN,condicionI,condicionD);
						}else{
							NodoBase aux = raiz;
							while(aux.tieneHermano())
								aux = aux.getHermanoDerecha();
							aux.setHermanoDerecha(new NodoOperacion(sym.REUN,condicionI,condicionD));
						}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expresion ::= expresion PROC expresion 
            {
              NodoBase RESULT =null;
		int condicionIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condicionIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase condicionI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicionD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						if(raiz==null){
							raiz = new NodoOperacion(sym.PROC,condicionI,condicionD);
						}else{
							NodoBase aux = raiz;
							while(aux.tieneHermano())
								aux = aux.getHermanoDerecha();
							aux.setHermanoDerecha(new NodoOperacion(sym.PROC,condicionI,condicionD));
						}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expresion ::= expresion DIF expresion 
            {
              NodoBase RESULT =null;
		int condicionIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condicionIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase condicionI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicionD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						if(raiz==null){
							raiz = new NodoOperacion(sym.DIF,condicionI,condicionD);
						}else{
							NodoBase aux = raiz;
							while(aux.tieneHermano())
								aux = aux.getHermanoDerecha();
							aux.setHermanoDerecha(new NodoOperacion(sym.DIF,condicionI,condicionD));
						}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expresion ::= expresion DIV expresion 
            {
              NodoBase RESULT =null;
		int condicionIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condicionIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase condicionI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicionD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						if(raiz==null){
							raiz = new NodoOperacion(sym.DIV,condicionI,condicionD);
						}else{
							NodoBase aux = raiz;
							while(aux.tieneHermano())
								aux = aux.getHermanoDerecha();
							aux.setHermanoDerecha(new NodoOperacion(sym.DIV,condicionI,condicionD));
						}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expresion ::= expresion INT expresion 
            {
              NodoBase RESULT =null;
		int condicionIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condicionIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase condicionI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicionD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						if(raiz==null){
							raiz = new NodoOperacion(sym.INT,condicionI,condicionD);
						}else{
							NodoBase aux = raiz;
							while(aux.tieneHermano())
								aux = aux.getHermanoDerecha();
							aux.setHermanoDerecha(new NodoOperacion(sym.INT,condicionI,condicionD));
						}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expresion ::= expresion UNI expresion 
            {
              NodoBase RESULT =null;
		int condicionIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condicionIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase condicionI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int condicionDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condicionDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase condicionD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
						if(raiz==null){
							raiz= new NodoOperacion(sym.UNI,condicionI,condicionD);
						}else{
							NodoBase aux = raiz;
							while(aux.tieneHermano())
								aux = aux.getHermanoDerecha();
							aux.setHermanoDerecha(new NodoOperacion(sym.UNI,condicionI,condicionD));
						}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= expresion EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase start_val = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // expresion ::= relacion 
            {
              NodoBase RESULT =null;
		int relacionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int relacionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase relacion = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
							
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

