
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 01 17:42:16 VET 2013
//----------------------------------------------------

package Interprete;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNI = 4;
  public static final int PUNTO = 20;
  public static final int MENOR = 14;
  public static final int MAYOREQ = 13;
  public static final int INT = 7;
  public static final int COMI = 19;
  public static final int ID = 23;
  public static final int NUM = 22;
  public static final int PRO = 3;
  public static final int COMA = 18;
  public static final int MAYOR = 12;
  public static final int EOF = 0;
  public static final int DIFERENTE = 11;
  public static final int DIV = 8;
  public static final int REUN = 9;
  public static final int error = 1;
  public static final int PROC = 6;
  public static final int EQ = 10;
  public static final int SEL = 2;
  public static final int NUEVA = 21;
  public static final int MENOREQ = 15;
  public static final int DPAREN = 17;
  public static final int DIF = 5;
  public static final int IPAREN = 16;
}

