
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 07 23:24:11 VET 2013
//----------------------------------------------------

package Interprete;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNI = 4;
  public static final int AND = 10;
  public static final int PUNTO = 23;
  public static final int MENOR = 17;
  public static final int MAYOREQ = 16;
  public static final int OR = 12;
  public static final int INT = 7;
  public static final int NOT = 11;
  public static final int COMI = 22;
  public static final int ID = 27;
  public static final int NUM = 26;
  public static final int PRO = 3;
  public static final int COMA = 21;
  public static final int MAYOR = 15;
  public static final int EOF = 0;
  public static final int DIFERENTE = 14;
  public static final int DIV = 8;
  public static final int FECHA = 24;
  public static final int REUN = 9;
  public static final int error = 1;
  public static final int PROC = 6;
  public static final int EQ = 13;
  public static final int SEL = 2;
  public static final int NUEVA = 25;
  public static final int MENOREQ = 18;
  public static final int DPAREN = 20;
  public static final int DIF = 5;
  public static final int IPAREN = 19;
}

